#!/bin/bash

#################################################################################
# FUNCTIONS
#################################################################################

##===============================================================================
#
# Create a fancy little progress bar
# https://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script
function progress_bar()
{
    # Process data
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*4)/10
    let _left=40-$_done

    # Build progressbar string lengths
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

    # Clear previous line
    # https://stackoverflow.com/questions/2388090/how-to-delete-and-replace-last-line-in-the-terminal-using-bash
    tput el

    # 1.2 Build progressbar strings and print the ProgressBar line
    # 1.2.1 Output example:
    # 1.2.1.1 Progress : [########################################] 100%
    printf "Progress: [${_fill// /\#}${_empty// /-}] ${_progress}%% - $f\r"
}

##===============================================================================
#
function process()
{
	# Initialize values
	local file=$1
	local dir=$2
	local header_file=$3
	local html_file="$dir/$(basename ${file%.*}).html"

	# Process markdown
	pandoc -s --toc --pdf-engine=xelatex --webtex --listings -o $html_file $file

	# Get the text from the file
	header=$(<$header_file)
	body=$(<$html_file)

	# Replace %content% with processed markdown
	echo "${header//__PLACEHOLDER__/$body}" > $html_file
}

#################################################################################
# SCRIPT
#################################################################################
outdir="www"
header_file="./html/template.html"

# Create directory and clear it
mkdir -p $outdir
rm -rf $outdir/*.html

# Get file count
files=(*.md)
cnt=${#files[@]}

# Loop through each markdown file in the directory
i=1
for f in "${files[@]}"
do
	# Output progress
	progress_bar $i $cnt

	# Process file
	process $f $outdir $header_file
	
	# Update index
	i=$((i+1))

done
