* Knowledge Base
:PROPERTIES:
:CUSTOM_ID: knowledge-base
:END:
This page is somewhat misleading. I provide links to general starting
points, but the idea is to have a free-flowing set of knowledge that can
be interconnected with one another. The idea is to separate yourself
from the idea of categorizing topics in your head and effectively
building mental barriers between these ideas. To reiterate, the links
before only provide general starting points for what you may be
interested in finding.

The set of references can be found in the =main.bib=.

* Control Theory
:PROPERTIES:
:CUSTOM_ID: control-theory
:END:
- [[file:nonlinear_control.md][Nonlinear Control]]

* Estimation
:PROPERTIES:
:CUSTOM_ID: estimation
:END:
[[file:estimation.md][Estimation]] is the process of attempting to
derive the true value of measurements taken from a system that are
subect to noise and/or bias.

** Optimal Estimation
:PROPERTIES:
:CUSTOM_ID: optimal-estimation
:END:
[[file:optimal_estimation.md][Optimal Estimation]], much like
estimation, attempts to estimate the true value from a measurement that
has been subject to noise and bias. This optimization method is known as
the [[file:kalman_filter.md][Kalman Filter]].

* Mathematics
:PROPERTIES:
:CUSTOM_ID: mathematics
:END:
** Calculus
:PROPERTIES:
:CUSTOM_ID: calculus
:END:
- [[file:derivatives.md][Derivatives]]

** Fuzzy Logic
:PROPERTIES:
:CUSTOM_ID: fuzzy-logic
:END:
- [[file:fuzzy_theory.html][Fuzzy Logic]]

** Linear Algebra
:PROPERTIES:
:CUSTOM_ID: linear-algebra
:END:
[[file:linear_algebra.md][Linear algebra]] is the branch of mathematics
concerning linear equations and their representation in vector spaces
and through matrices.

*** Vectors
:PROPERTIES:
:CUSTOM_ID: vectors
:END:
[[file:vectors.md][Vectors]]

** Set Theory
:PROPERTIES:
:CUSTOM_ID: set-theory
:END:
The theory of [[file:set_theory.md][sets]] in a nutshell.

** Quaternions
:PROPERTIES:
:CUSTOM_ID: quaternions
:END:
Theory of [[file:quaternion_theory.md][quaternions]] in a nutshell

** Queue Theory
:PROPERTIES:
:CUSTOM_ID: queue-theory
:END:
[[file:queueing_theory.html][Queueing Theory]]

* Optimization
:PROPERTIES:
:CUSTOM_ID: optimization
:END:
Below are some sections on optimization types.
[[file:optimization_for_engineers_class.md][This link has a set of notes
from optimization for engineers]].

** Parametric Programming
:PROPERTIES:
:CUSTOM_ID: parametric-programming
:END:
Parametric programming is a type of optimization, where the optimization
problem is solved as a function of one or multiple parameters.

** Linear Programming
:PROPERTIES:
:CUSTOM_ID: linear-programming
:END:
Process of optimization by setting up the worlds largest set of linear
equations

*** Fuzzy Linear Programming
:PROPERTIES:
:CUSTOM_ID: fuzzy-linear-programming
:END:
[[file:fuzzy_lin_prog.html][Fuzzy Linear Programming]]

*** Stochastic Programmming
:PROPERTIES:
:CUSTOM_ID: stochastic-programmming
:END:
[[file:stochastic_prog.html][Stochastic Programming]] is a framework for
modeling optimizaiton problems that involve uncertainty. A stochastic
program is an optimization problem in which som eor all problem
parameters are uncertain, but follow known probability distributions.

* Programming
:PROPERTIES:
:CUSTOM_ID: programming
:END:
** MATLAB
:PROPERTIES:
:CUSTOM_ID: matlab
:END:
MATLAB is sorta butts, but here are some useful
[[file:matlab_tips.md][tips]]
