#!/bin/sh

#################################################################################
# FUNCTIONS
#################################################################################

##===============================================================================
#
# Create a fancy little progress bar
# https://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script
function progress_bar()
{
    # Process data
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*4)/10
    let _left=40-$_done

    # Build progressbar string lengths
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

    # 1.2 Build progressbar strings and print the ProgressBar line
    # 1.2.1 Output example:
    # 1.2.1.1 Progress : [########################################] 100%
    printf "\rProcessing $s: [${_fill// /\#}${_empty// /-}] ${_progress}%% \r"
}

##===============================================================================
#
function process()
{
	# Initialize values
	file=$1
	dir=$2
	header=$3
	html_file="$dir/$(basename ${file%.*}).html"

	# Process markdown
	pandoc -o $html_file $file

	# Get the text from the file
	text=$(cat $html_file)

	# Replace %content% with processed markdown
	awk -v t="$text" '{ gsub(/%content%/, t); print}' $header > $html_file
}

#################################################################################
# SCRIPT
#################################################################################
outdir="www"
header="./html/template.html"

# Create directory and clear it
mkdir -p $outdir
rm -rf $outdir/*.html

# Get file count
files=(*.md)
cnt=${#files[@]}

# Loop through each markdown file in the directory
i=0

for f in "${files[@]}"
do
	# Calculate progress
	i=$((i+1))
	progress=$(($i*100/$cnt))

	# Output progress
	progress_bar $i $progress

	# Process file
	process $f $outdir $header
done
