* Writing a X Window Manager
:PROPERTIES:
:CUSTOM_ID: writing-a-x-window-manager
:END:
** Window Hierarchy
:PROPERTIES:
:CUSTOM_ID: window-hierarchy
:END:
Windows are organized into a tree hierarchy. The root of the hierarchy
is the root window, a virtual, invisible window that ha the same size as
the screen and is always present. Top level windows are direct children
of the root window. UI elements within a top level window are
descendants of that window. This hierarchy also enforces that the child
is clipped to the boundaries of its parent.

** Substructure Redirection
:PROPERTIES:
:CUSTOM_ID: substructure-redirection
:END:
Substructure redirection is the mechanism that allows a window manager
to intercept requests to draw window decorations, resize, etc. A window
manager must subscribe to /substructure redirection/ on the root window
so that all requests are passed through the window manager.

** Reparenting
:PROPERTIES:
:CUSTOM_ID: reparenting
:END:
The process of reparenting is what allows windows frames to be drawn
(max, min, hide buttons). When a window is created, the window manager
is notified and makes the window a child of a frame generated by the
window manager. Because the window is no longer a direct descendent from
the root window the window manager cannot modify it UNLESS it has also
registed for substructure redirection on each frame window it creates.

* Sources
:PROPERTIES:
:CUSTOM_ID: sources
:END:
[[https://jichu4n.com/posts/how-x-window-managers-work-and-how-to-write-one-part-i/.md][How
X Window Managers Work, And How To Write One]]
