#+title: Sampling theorem
*The sampling process converts a continuous time signal into a signal of discrete time*. What this means is that we basically end up with a sequence of numbers.

#+begin_theorem
If a signal $s(t)$ containns no frequencies outside $B$ Hz, it is completely determined by its values at a sequence of points spaced $< \frac{1}{2B}$ seconds apart.
#+end_theorem

*That means for a band limited signal of band $B$ we get pefect reconstruction if we sample at a rate $B < f_s/2$*!

Lets consider the periodic summation of $S(f)$. Let the sampling rate $f_s = 1/T$.

\begin{equation*}
\begin{array}{ll}
S_{\text{periodic sum}}(f) & = \sum_{k=\-infty}^{\infty} S(f-kf_s) \\
& = \sum_{k=\-infty}^{\infty} T s(nT) e^{-j2\pi nTf} \\
\end{array}
\end{equation*}

What does this mean? Copies of $S(f)$ in multiples of $f_s$, are transated are added. For bandlimited signals ($X(f) = 0\; |f| \ge B$ and sufficiently large $f_s$), it is possible for copies to be distinct from each other.

If the Nyquist criterion is not satisfied, adjacent copies overlap which implies that the [[https://en.wikipedia.org/wiki/Aliasing][aliasing affect]] will occur (overlapping frequencies). This is why bands are applied to frequencies (low pass or anti-aliasing filter) before sampling occurs so that we can guarantee that this does not occur.

* Interpolation formula
$S_{\text{periodic sum}}(f)$ can be used to recover $S(f)$ ($k = 0$). That is we can say for a $H(f) = \begin{cases} 1 & |f| < B \\ 0 & |f| > f_s-B \end{cases}$ (the critical point being $B = \frac{f_s}{2}$.

\begin{equation*}
\begin{array}{ll}
S(f) & = H(f)S_{\text{periodic sum}}(f) \\
\end{array}
\end{equation*}

Use the fact that 

$$
H(f) = \text{rect}(f/f_s) = 
\begin{cases}
1 & |f| < \frac{f_s}{2} \\ 
0 & |f| > \frac{f_s}{2} 
 \end{cases}
$$

Se we can write

\begin{equation*}
\begin{array}{ll}
S(f) & = \text{rect}(f/f_s)S_{\text{periodic sum}}(f) \\
& = \text{rect}(Tf)\sum_{n=\infty}^{\infty} Ts(nT) e^{-j2\pi nTf} \\
& = \sum_{n=\infty}^{\infty} s(nT)T \text{rect}(Tf) e^{-j2\pi nTf} \\
\end{array}
\end{equation*}

Now if we look carefully we see that $s(nT)T \text{rect}(Tf) e^{-j2\pi nTf} = F(sinc(t-nT)/T)$. If we take the inverse Fourier transform on both sides of the equation we find

\begin{equation*}
\begin{array}{ll}
s(t) & = \sum_{n=\infty}^{\infty} s(nT) sinc((t-nT)/T) \\
\end{array}
\end{equation*}

where the $sinc(\cdot)$ part of the summation is called the sinc interpolator.