#+title: Lipschitz Condition

* What is a Lipschitz Condition?
:PROPERTIES:
:CUSTOM_ID: what-is-a-lipschitz-condition
:END:
This is a basic introduction to Lipschitz conditions within the context
of differential equations. Lipschitz conditions are connected with
"contrastive mappings", which have important applications to the
existence, uniqueness and approximation of solutions to equations -
including ordinary differential equations.

** Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:
General first order initial value problem

\[
    x' = f(t,x),\; x(\tau) = A
\]

where \(x' = \frac{dx}{dt}\)

Much of the theory for IVP, its variation involves a so-called Lipschitz
condition. This condition is the cornerstone for gaining information
about solutions to the IVP, such as existence, uniqueness and
approximation.

#+begin_example
We say $f$ satisfies a Lipschitz condition on a set $D$ if there is a constant $L \geq 0$ such that
#+end_example

\[
    |f(t,u) - f(t,v)| \leq L |u-v|,\; \text{for all } (t,v),(t,v)\in D
\]

** When does a Lipschitz condition hold?
:PROPERTIES:
:CUSTOM_ID: when-does-a-lipschitz-condition-hold
:END:
Given some \(f\) and \(D\), when does the Lipschitz Condition hold?

*Example* Let \(D = \mathbb{R}^2\) and lat \(f(t,u) := t^2 + 2u\). For
each \((t,u), (t,v) \in D\) consider

\[
\begin{array}{ll}
    | f(t,u) - f(t,v) | & = | (t^2 + 2u) - (t^2 - 2v) | \\
                            & = 2|u-v|
\end{array}
\]

#+begin_example
*Lemma*: Let $D$ be a rectangle
#+end_example

\[
    R:= \{(t,p) : t \in ![pic](a,b), |p-A| \leq B\}
\]

#+begin_example
or the infinite strip
#+end_example

\[
    S:= \{(t,p) : t \in ![pic](a,b), |p-A| \leq \infty \}
\]

#+begin_example
If $f : D \rightarrow \mathbb{R}$ and $\frac{\partial f}{\partial y}$ exists, is continuous and there is some constant $K \geq 0$ such that
#+end_example

\[
    \left| \frac{\partial f}{\partial y}(t,y) \right| \leq K,\; \text{for all } (t,y) \in D
\]

#+begin_example
then the Lipschitz Condition holds with $L=K$
#+end_example

** Local Lipshitz
:PROPERTIES:
:CUSTOM_ID: local-lipshitz
:END:
#+begin_example
*Theorem*: Let $f:R\rightarrow \mathbb{R}$ be continuous and let $(\tau A) \in R$. If there is a constant $L \geq 0$ satisfying
#+end_example

$$ |f(t,u) - f(t,v)| \leq L |u-v|,; \text{for all } (t,v),(t,v)\in R

$$

#+begin_example
then the IVP has a unique solution $x=x(t)$ on some interval containing $\tau$.

*Corollary*: Let $f:R\rightarrow \mathbb{R}$ be continuous and let $\frac{\partial f}{\partial y}$ exists and is continuous on $R$ and there is dome constant $K \geq 0$ such that
#+end_example

\[
    \left| \frac{\partial f}{\partial y}(t,y) \right| \leq K,\; \text{for all } (t,y) \in D
\]

#+begin_example
then the IVP has a unique solution $x=x(t)$ on some interval containing $\tau$.
#+end_example

* References
:PROPERTIES:
:CUSTOM_ID: references
:END:
- [[https://www.youtube.com/watch?v=Cnc83B3C2pY.md][YouTube Video]]
