#+LATEX_HEADER: \newtheorem{definition}{Definition}[section]

* Signals and systems, Oppenheim, A. V., & Willsky, A. S., , (1996) :book:

See [[cite:&oppenheim-1996-signal-system]]

* Signals and Systems
** Introduction
There is an analytical framework - that is, a language for describing signals and systems and an extremely powerful set
of tools for analyzing them-that applies equally well to problems in many fields. In this chapter, we begin our
development of the analytical framework for signals and systems by introducing their mathematical description and
representations.

** Continuous-Time And Discrete-Time Signals
Signals can be represented in many ways, but in all cases the information is contained in a pattern of variations of
some form. Signals are represented mathematically as a function of one or more independent variable. This book, however,
will focus on solving signals of a single independent variable.

*** Signal Energy And Power
In many, but not all, applications, the signals we consider are directly related to physical quantities capturing power
and energy in a physical system. As an example, for a voltage passing through a resister the power at any instant is
calculated as $p(t) = \frac{v^2(t)}{R}$ from which we can write the total energy expended over an interval as

\begin{equation}
\int_{t_1}^{t_2} \frac{v^2(t)}{R} dt
\end{equation}

and the average power over the interval being

\begin{equation}
\frac{1}{t_2 - t_1} \int_{t_1}^{t_2} \frac{v^2(t)}{R} dt
\end{equation}

Although a direct equation like this may not be found for all applications, it is a common and worthwhile convention to
use similar terminology for power and energy for /any/ continuous-time or discrete-time signal. It is moreover
convenient to consider signals that take on complex values. In this case, the total energy over the time interval $t_1 \le
t \le t_2$ in a continuous-time signal x(t) is defined as

#+name: eq:power-continuous
\begin{equation}
\int_{t_1}^{t_2} |x(t)|^2 dt
\end{equation}

and similarly for discrete signals

#+name: eq:power-discrete
\begin{equation}
\sum_{n_1}^{n_2} |x[t]|^2
\end{equation}

and their respective averages found by dividing by their respective time intervals. Furthermore, in many systems it is
of interest to examine the power and energy of signals over an infinite interval. That is autoref:eq:power-continuous
and autoref:eq:power-discrete with lower limit of $-\infty$ and upper limit of $\infty$. With this definition, three important
classes of signals arise:

+ Finite total energy $E_{\infty} < \infty$. Such signals have an average of zero power $\begin{cases} 1 & 0 \le t \le 1\\ 0 &
  \text{otherwise} \end{cases}$.
+ Finite average power $P_{\infty} < \infty$. Such signals have an infinite total energy ($x[n] = 4$)
+ Neither average power nor total energy are finite ($x(t) = t$).

** Transformations Of The Independent Variable
A central concept in signal and system analysis is that of the transformation of a signal. For example, in an aircraft
control system, signals corresponding to the actions of the pilot are transformed by electrical and mechanical systems
into changes in aircraft thrust or the positions of aircraft control surfaces such as the rudder or ailerons, which in
tum are transformed through the dynamics and kinematics of the vehicle into changes in aircraft velocity and heading.

*** Examples Of Transformations Of The Independent Variable
There are three basic transformations for a signal:

+ Time shift: $x[n] \rightarrow x[n-n_0]$
+ Time reversal: $x[n] \rightarrow x[-n]$
+ Time scaling: $x[n] \rightarrow x[\alpha n]\; \alpha \in \mathbb{R}$

Putting these together can get a total transformation of $x(\alpha t + \beta)$.

Transformations of the independent variable are extremely useful in signal and system analysis. These transformations
are also important in defining and examining some important properties of signals.

*** Periodic Signals
A periodic signal is that of one that repeats on some interval. Mathematically it is represented as

#+name: eq:periodicsignalcontinuous
\begin{equation}
x(t) = x(t + T)
\end{equation}

We say that $x(t)$ is periodic with period $T$. The fundamental period $T_0$ of $x(t)$ is the smallest positive value of $T$
for which autoref:eq:periodicsignalcontinuous holds. Similarly, for discrete signals we find

#+name: eq:periodicsignaldiscrete
\begin{equation}
x[n] = x[n + N]
\end{equation}

We say that $x[n]$ is periodic with period $N$. The fundamental period $N_0$ of $x[n]$ is the smallest positive value of
$N$.

*** Even And Odd Signals
A signal $x(t)$ or $x[n]$ is referred to as an even signal if it is identical to its time-reversed counterpart, i.e., with
its reflection about the origin.

\begin{equation}
x(t) = x(-t)
\end{equation}

A signal is odd if

\begin{equation}
x(-t) = -x(t)
\end{equation}

Furthermore, odd signals must necessarily be $0$ at $t=0$. This is true for discrete signals, just substitute $x(t)$ for
$x[n]$.

An important fact is that any signal can be broken into a sum of two signals, one of which is even and one of which is
odd. That is

\begin{equation}
x(t) = \mathcal{E}\{x(t)\} + \mathcal{O}\{x(t)\}
\end{equation}

Where the even and odd operators are defined as

\begin{equation}
\begin{array}{c}
\mathcal{E}\{x(t)\} = \frac{1}{2}[x(t) + x(-t)] \\
\mathcal{O}\{x(t)\} = \frac{1}{2}[x(t) - x(-t)] \\
\end{array}
\end{equation}

** Exponential And Sinusoidal Signals
